SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBC_PLANO_ACAO_VIDA](
	[ID_VIDA] [int] IDENTITY(1,1) NOT NULL,
	[TIPO] [varchar](200) NOT NULL,
	[ID_PLANO] [int] NOT NULL,
	[ID_STATUS_PLANO] [int] NOT NULL,
	[USUARIO_CRIACAO] [int] NOT NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
	[TEXTO] [varchar](2000) NOT NULL,
 CONSTRAINT [PK_TBC_PLANO_ACAO_VIDA] PRIMARY KEY CLUSTERED 
(
	[ID_VIDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_VIDA] ADD  CONSTRAINT [DF_TBC_PLANO_ACAO_VIDA_DATA_CRIACAO]  DEFAULT (getdate()) FOR [DATA_CRIACAO]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_VIDA]  WITH CHECK ADD  CONSTRAINT [FK_TBC_PLANO_ACAO_VIDA_TBC_PLANO_ACAO] FOREIGN KEY([ID_PLANO])
REFERENCES [dbo].[TBC_PLANO_ACAO] ([ID_PLANO])
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_VIDA] CHECK CONSTRAINT [FK_TBC_PLANO_ACAO_VIDA_TBC_PLANO_ACAO]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_VIDA]  WITH CHECK ADD  CONSTRAINT [FK_TBC_PLANO_ACAO_VIDA_TBC_PLANO_ACAO_STATUS] FOREIGN KEY([ID_STATUS_PLANO])
REFERENCES [dbo].[TBC_PLANO_ACAO_STATUS] ([ID_STATUS])
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_VIDA] CHECK CONSTRAINT [FK_TBC_PLANO_ACAO_VIDA_TBC_PLANO_ACAO_STATUS]
GO
