SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBC_PLANO_ACAO](
	[ID_PLANO] [int] IDENTITY(1,1) NOT NULL,
	[NOME_PLANO] [varchar](200) NOT NULL,
	[ID_STATUS_PLANO] [int] NOT NULL,
	[ID_AREA_RESPONSAVEL] [int] NOT NULL,
	[ID_CAUSA_RAIZ] [int] NOT NULL,
	[REGIONAL] [varchar](20) NOT NULL,
	[UF] [char](2) NOT NULL,
	[MUNICIPIO] [varchar](300) NOT NULL,
	[DATA_INICIO_PLANO] [date] NOT NULL,
	[DATA_PREVISAO_TERMINO] [date] NULL,
	[DATA_CONCLUSAO] [date] NULL,
	[USUARIO_CRIACAO] [int] NOT NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
	[USUARIO_ULT_ALTERACAO] [int] NOT NULL,
	[DATA_ULT_ALTERACAO] [datetime] NOT NULL,
 CONSTRAINT [PK_TBC_PLANO_ACAO] PRIMARY KEY CLUSTERED 
(
	[ID_PLANO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO] ADD  CONSTRAINT [DF_TBC_PLANO_ACAO_DATA_CRIACAO]  DEFAULT (getdate()) FOR [DATA_CRIACAO]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO] ADD  CONSTRAINT [DF_TBC_PLANO_ACAO_DATA_ULT_ALTERACAO]  DEFAULT (getdate()) FOR [DATA_ULT_ALTERACAO]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO]  WITH CHECK ADD  CONSTRAINT [FK_TBC_PLANO_ACAO_TBC_PLANO_ACAO_AREA_RESPONSAVEL] FOREIGN KEY([ID_AREA_RESPONSAVEL])
REFERENCES [dbo].[TBC_PLANO_ACAO_AREA_RESPONSAVEL] ([ID_AREA_RESPONSAVEL])
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO] CHECK CONSTRAINT [FK_TBC_PLANO_ACAO_TBC_PLANO_ACAO_AREA_RESPONSAVEL]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO]  WITH CHECK ADD  CONSTRAINT [FK_TBC_PLANO_ACAO_TBC_PLANO_ACAO_CAUSA_RAIZ] FOREIGN KEY([ID_CAUSA_RAIZ])
REFERENCES [dbo].[TBC_PLANO_ACAO_CAUSA_RAIZ] ([ID_CAUSA_RAIZ])
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO] CHECK CONSTRAINT [FK_TBC_PLANO_ACAO_TBC_PLANO_ACAO_CAUSA_RAIZ]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO]  WITH CHECK ADD  CONSTRAINT [FK_TBC_PLANO_ACAO_TBC_PLANO_ACAO_STATUS] FOREIGN KEY([ID_STATUS_PLANO])
REFERENCES [dbo].[TBC_PLANO_ACAO_STATUS] ([ID_STATUS])
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO] CHECK CONSTRAINT [FK_TBC_PLANO_ACAO_TBC_PLANO_ACAO_STATUS]
GO
