SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBC_PLANO_ACAO_AREA_RESPONSAVEL](
	[ID_AREA_RESPONSAVEL] [int] IDENTITY(1,1) NOT NULL,
	[AREA_RESPONSAVEL] [varchar](200) NOT NULL,
	[FLG_ATIVO] [tinyint] NOT NULL,
	[USUARIO_CRIACAO] [int] NOT NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
 CONSTRAINT [PK_TBC_PLANO_ACAO_AREA_RESPONSAVEL] PRIMARY KEY CLUSTERED 
(
	[ID_AREA_RESPONSAVEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_AREA_RESPONSAVEL] ADD  CONSTRAINT [DF_TBC_PLANO_ACAO_AREA_RESPONSAVEL_FLG_ATIVO]  DEFAULT ((1)) FOR [FLG_ATIVO]
GO
ALTER TABLE [dbo].[TBC_PLANO_ACAO_AREA_RESPONSAVEL] ADD  CONSTRAINT [DF_TBC_PLANO_ACAO_AREA_RESPONSAVEL_DATA_CRIACAO]  DEFAULT (getdate()) FOR [DATA_CRIACAO]
GO
